### PR TITLE
Add @EnableDopplerMetrics for exporting to doppler (loggregator)

### PR DESCRIPTION
**Pull request by dsyer**
If the "lattice" profile is active the app now looks for DOPPLER_HOST,
DOPPLER_PORT and DOPPLER_ORIGIN and pumps metrics to doppler/metron.

Requires local build and install of dsyer/doppler-metrics-sample. See the
README there for the iptables stunt that you have to pull to accept the
metrics.

### CODE REVIEW

**Comment by markfisher** [comment]
Dave, I am getting a build failure on this branch:

```
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve org.springframework.boot:spring-boot-gradle-plugin:1.3.0.BUILD-SNAPSHOT.
     Required by:
         :xolpoc:unspecified
      > Could not parse POM /Users/mark/.m2/repository/org/springframework/boot/spring-boot-gradle-plugin/1.3.0.BUILD-SNAPSHOT/spring-boot-gradle-plugin-1.3.0.BUILD-SNAPSHOT.pom
         > Unable to resolve version for dependency 'org.springframework.boot:spring-boot-dependency-tools:jar'
```

**Comment by dsyer** [comment]
Looks like a Maven download network issue. It doesn't say it can't download it, just that it is unreadable (so probably it's HTML from a WiFi hotspot or something)?

**Comment by markfisher** [comment]
With `--stacktrace` I get the following:

```
Caused by: org.gradle.api.internal.artifacts.ivyservice.ModuleVersionResolveException: Could not resolve org.springframework.boot:spring-boot-gradle-plugin:1.3.0.BUILD-SNAPSHOT.
Required by:
    :xolpoc:unspecified
    at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainDependencyResolver.resolve(RepositoryChainDependencyResolver.java:72)
    ...
Caused by: java.lang.NullPointerException
    at org.gradle.api.internal.artifacts.repositories.resolver.MavenLocalResolver.isOrphanedPom(MavenLocalResolver.java:49)
```

Is there some additional upstream requirement? Anything that's needed here (including the doppler-metrics-sample local build) should be added to the README.

**Comment by markfisher** [comment]
I had a local boot branch checked out from when that was necessary for the doppler metrics last week. I merged the upstream master branch and now I'm past the resolution error for the gradle plugin.

However, I am now back to 68 build ERRORS related to unresolved dependencies on XD classes.

**Comment by markfisher** [comment]
I got past that after building XD locally and running `gradle install`. I guess the snapshot POM issue is still unresolved.

**Pull request merged**
